services:
  - type: web
    name: mindhive-chatbot-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install uvicorn
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "true" 