# Streamlit secrets configuration
# For deployment, replace with your actual backend URL

BACKEND_URL = "http://localhost:8000"

# For production deployment:
# BACKEND_URL = "https://your-backend-url.railway.app" 